### ISSUE TITLE
Wat heb je geleerd?

### ISSUE THREAD

**Issue by vasilisvg** [BerendPronk/minor-cssttr#13]
Ik ben natuurlijk heel benieuwd of je nieuwe dingen hebt geleerd. En als ik mooie resultaten zie zoals wat jij hebt gemaakt dan vraag ik me af of je echt wel iets nieuws hebt geleerd, of dat je dit allemaal al kon.

**Comment by BerendPronk** [comment]
Hallo Vasilis,

Bedankt voor alle ijzersterke feedback, net als bij Rik merk ik dat er nog altijd handigheden te ontdekken zijn in CSS.

Naast de feedback die jullie beide gegeven hebben, heb ik evengoed veel geleerd. Diverse hoofdstukken uit het boek tackelde nieuwe onderwerpen voor mij, zoals: De pseudo-random achtergrond, de de-emphasizing met behulp van de target selector (alles betreffende de target selector was nieuw voor mij), 'extending the clickable area' (waar ik wist hoe ik het toe kon passen, alleen niet begreep hoe belangrijk zulke dingen zijn voor de eindgebruiker), het toepassen van een font voor specifieke karakters en de sibling count.
Daarnaast heb ik veel geleerd over usability in het geheel. Over het verduidelijken van de focus, zodat men zonder muis ook op een fijne manier door de website kan navigeren.
