### ISSUE TITLE
RATING

### ISSUE THREAD

**Issue by rikschennink** [BerendPronk/minor-cssttr#3]
Het actieve item is niet heel duidelijk (lijkt ook niet in het midden uit te lijnen, dit is op Chrome OSX). Misschien kan je de smileys animeren zodra een selectie veranderd? :-)

**Comment by BerendPronk** [comment]
Dat kan ik zeker doen, maar daarvoor dien ik wel de HTML te wijzigen. Het is nu echt een pain om te werken met labels die voor de inputs staan. Aan de hand van een adjacent selector kan ik het label stylen / animeren wanneer de input gecheckt is.

Ik heb mijzelf aangehouden om niets, op het toevoegen van sections en een link voor het modal na, aan de HTML te doen voor deze eerste oplevering, maar zal het volgende keer anders doen ;)

**Comment by rikschennink** [comment]
Je mag gewoon HTML toevoegen, zeker als dat de UX ten goede komt (dus als je een extra element kan verdedigen). Ik zeg, doen!
