### ISSUE TITLE
CSS

### ISSUE THREAD

**Issue by rikschennink** [BerendPronk/minor-cssttr#6]
# 10
Ik zou hier gewoon id gebruiken dit voelt een beetje dubbel op, resulteert ook in deze statements die ##{$navigation} wat vaag zijn misschien. Beter is daarnaast om op classes te stylen om specificiteit laag te houden.

# 22

transforms lekker zonder prefixes doen

# 44
beter niet, dit reset zo alle default marges en paddings, dat kan soms voor vreemd gedrag zorgen (zo veroorzaakt dit statement vroegàh het niet werken van button tags in IE). Beter is per element bepalen wat wel en niet aan te passen.

# 63
rem & em is hetzelfde op media query level, allebei prima, just so you know.

**Comment by BerendPronk** [comment]
# 10

Begrijp ik! Door te werken met modules tijdens mijn stage heb ik dit een beetje aangehouden ;) Zal het wijzigen!

# 22

Maar hoe zit het dan met: http://shouldiprefix.com/#transforms?

# 44

:+1: Gewenning

# 63

Dit zal je me volgende week maar even duidelijk moeten maken, ben benieuwd

Ik werk nu voor het eerst met Git issues en pull-requests en merk dat er veel mails verstuurd worden bij replies. Als je het fijn vindt, zal ik volgende keer niet op ieder issue reageren ;)

**Comment by rikschennink** [comment]
Behoorlijk email bombardement :) Reageer maar gewoon, geen probleem!

# 22 
Dat moet je zelf bepalen per project, elk project heeft weer eigen randvoorwaarden. Als je transforms gaat activeren op oude browsers betekent dat ook dat het misschien op oude systemen gaat draaien die helemaal niet de capaciteit hebben om die transforms goed te renderen, dan kan je er beter voor kiezen ze weg te laten. Zo'n website is een goede richtlijn maar ik zou toch altijd even in de caniuse.com kijken http://caniuse.com/#search=transforms en dan bepalen wat voor jouw project het best past.

# 63 
em & rem is allebei op window niveau gelijk aan root (eerste parent van em is root (html) en rem kijkt ook naar root (root em) dus daardoor kan je ze allebei inzetten.

**Comment by BerendPronk** [comment]
Keigoede feedback en tips. Veel dank!

Allemaal kleine dingen die ik nog niet wist, maar toch erg handig zijn.
